- id:
- name:
- description:
- type:
- release-date:
- release-number:
- work-package:
- WP:
- pilot:
- Pilots:
- keywords:
- changelog:
- licence:
- release link:
- image:
- logo:
- demo:
- links:
- credits:
- related-components:
- bibliography:
